### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/wp-dev-recipes#1]
# Problem
* We need a logo designed

# Requirements
* Needs to match [aspect ratio of Nuxt Docs](https://content.nuxtjs.org/themes/docs#static)
* Needs to work with "light mode" and "dark mode"

**Comment by jaydrogers** [comment]
@danpastori Are there any logo concepts that you like?

# 1
![1](https://user-images.githubusercontent.com/3174134/93258062-5ea64780-f763-11ea-999c-da9cfac4b52f.png)

# 2
![2](https://user-images.githubusercontent.com/3174134/93258087-682faf80-f763-11ea-9191-0770d56d680d.png)

# 3
![3](https://user-images.githubusercontent.com/3174134/93258095-6bc33680-f763-11ea-95ee-774d26c5bbec.png)

**Comment by danpastori** [comment]
These are awesome! I really like the 3rd option!
