### ISSUE TITLE
OG Image is not loading

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/wp-dev-recipes#16]
## Issue description
When sharing https://wp-dev-recipes.serversideup.net/, the OG image is not loading on Twitter.

## Steps to reproduce the issue

1.  Go to https://cards-dev.twitter.com/validator
2.  Enter https://wp-dev-recipes.serversideup.net/
3.  You'll see the image does not load

## What is expected?
It should pull https://wp-dev-recipes.serversideup.net/preview.png

## Additional details / screenshots
<img width="1152" alt="Screen Shot 2020-10-04 at 2 56 55 PM" src="https://user-images.githubusercontent.com/3174134/95025808-1be4da80-0652-11eb-97db-583048df132e.png">

**Comment by jaydrogers** [comment]
I am also experiencing the issue here: https://github.com/serversideup/self-hosted-email-guide/issues/2

**Comment by szepeviktor** [comment]
Go back to the roots: https://validator.w3.org/nu/?doc=https%3A%2F%2Fwp-dev-recipes.serversideup.net%2F

**Comment by szepeviktor** [comment]
@jaydrogers (aka. Superman) is manufacturing HTML code and forgets to validate it: less Kryptonite!

**Comment by szepeviktor** [comment]
🍏 

![kép](https://user-images.githubusercontent.com/952007/95026958-3f7d4480-0695-11eb-9348-f393938805be.png)

**Comment by szepeviktor** [comment]
No! We must dig deeper.
The very same HTML on my website works, does not work on the live site.
My website does not even have `preview.png`

**Comment by jaydrogers** [comment]
Your PR definitely fixed it. Thanks @szepeviktor!!
 <img width="1008" alt="Screen Shot 2020-10-04 at 4 38 30 PM" src="https://user-images.githubusercontent.com/3174134/95027687-11c9d880-0660-11eb-82a8-309b532edef0.png">

**Comment by szepeviktor** [comment]
Please send the usual €1 000 000 :)
💶💶💶
