### ISSUE TITLE
My fantasy world fails ☁

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/wp-dev-recipes#20]
> Modular, reusable code snippets for all WordPress devs. 

People using snippets won't ever be experts as they do not read/understand core's source code.

# 😿😿😿

**Comment by jaydrogers** [comment]
In the WordPress world, code snippets are much better than installing a plugin to solve the problem. We just have to start with baby steps 😃

**Comment by szepeviktor** [comment]
Oh! I see!

Do you mean something like my nice landfill?
https://github.com/szepeviktor/wordpress-plugin-construction
