### ISSUE TITLE
Where should snippets land in your WordPress installation?

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/wp-dev-recipes#21]
- I put my anti-problem snippets into `mu-plugins/` https://github.com/szepeviktor/debian-server-tools/tree/master/webserver/wordpress
- there are bigger ones (from [the landfill](https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-disable-xmlrpc/disable-xmlrpc.php) mentioned previously) still go as MU plugins
- there are [even bigger ones published on WP.org](https://wordpress.org/plugins/tiny-cdn/) they go of course to `plugins/` - still not full-featured plugins
- unsustainable: put code into to-be-updated themes' `functions.php`
- still a turmoil: put non content related code into your custom theme - many guys do this, I think this is a collision 💥
- wouldn't choose to put snippets into a child theme: a "theme" is responsible for displaying content, all other things should live in their separate places

**Comment by danpastori** [comment]
@szepeviktor With WP Dev Recipes, they can be mixed into a theme or plugin. Essentially they are small features that you can add to a custom plugin or theme to add more functionality. I'll be doing my best dividing up what recipes work in themes vs plugins or with other plugins (WooCommerce, Yoast, etc.). The issue definitely is that you can put "theme" code into a plugin and "plugin" code into a theme if you choose. I try to ensure those are separate, but other devs may not feel that's the case.

**Comment by szepeviktor** [comment]
Okay.
Maybe I'm alone in the world who puts non feature complete plugins/snippets into `mu-plugins/`
