### ISSUE TITLE
Create OG Image

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/wp-dev-recipes#4]
# Problem
* Sharing recipes are not encouraging engagement because they lack the rich content for social sharing
# Solution
* Create OG image with the logo for when links are shared

**Comment by jaydrogers** [comment]
@danpastori What do you think of this social image?

[View the HQ version in Figma →](https://www.figma.com/file/8AblTC8hOYxKry9KETjm07/WP-Dev-Recipes?node-id=1%3A2)

![Social Image](https://user-images.githubusercontent.com/3174134/93544045-b2ab5a80-f922-11ea-9355-fd7812781be8.png)

**Comment by jaydrogers** [comment]
Heaven forbid, I forgot to capitalize the `P` in WordPress.

Here is the latest version.

![Social Image](https://user-images.githubusercontent.com/3174134/93544260-3d8c5500-f923-11ea-961b-fe71c7dbbb84.png)

**Comment by danpastori** [comment]
LOVE IT! Let's use it!
